swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - multipart/form-data
produces:
  - "application/json"

# Paths supported by the server application
paths:
  /api/upload:
    get:
      operationId: "apps.upload.views.Upload"
      tags:
        - "Upload"
      summary: "The upload api"
      parameters:
        - in: formData
          name: upfile
          type: file
          description: "Upload files to users folders"

      responses:
        200:
          description: "Successful upload!"

